# -*- coding: utf-8 -*-
"""QuantStats 本地化工具。

这个模块集中维护英文展示文本到中文展示文本的映射，避免在
reports / plots / stats 等文件中到处散落硬编码中文字符串。
本地化只处理展示层，不改变任何收益、风险和统计指标的计算逻辑。
"""

from __future__ import annotations

import re
from typing import Any

import pandas as pd


TEXT_MAP = {
    "Strategy": "策略",
    "Benchmark": "基准",
    "Returns": "收益率",
    "Return": "收益",
    "Cumulative Returns": "累计收益",
    "Cumulative Return": "累计收益",
    "Total Return": "总收益",
    "Daily Returns": "日收益",
    "Daily Return": "日收益",
    "Daily Active Returns": "日主动收益",
    "Monthly Returns": "月度收益",
    "Monthly Active Returns": "月度主动收益",
    "Weekly Returns": "周度收益",
    "Quarterly Returns": "季度收益",
    "Annual Returns": "年度收益",
    "EOY Returns": "年度收益",
    "EOY Returns vs Benchmark": "年度收益 vs 基准",
    "Distribution of Returns": "收益分布",
    "Distribution of Weekly Returns": "周度收益分布",
    "Distribution of Monthly Returns": "月度收益分布",
    "Distribution of Quarterly Returns": "季度收益分布",
    "Distribution of Annual Returns": "年度收益分布",
    "Return Quantiles": "收益分位数",
    "Drawdown": "回撤",
    "Drawdowns": "回撤",
    "Underwater Plot": "回撤水下图",
    "Worst 5 Drawdowns": "最差 5 次回撤",
    "Worst 10 Drawdowns": "最差 10 次回撤",
    "Worst Drawdown Periods": "最差回撤区间",
    "Rolling Volatility": "滚动波动率",
    "Rolling Sharpe": "滚动夏普",
    "Rolling Sortino": "滚动索提诺",
    "Rolling Beta to Benchmark": "相对基准滚动 Beta",
    "Volatility": "波动率",
    "Sharpe": "夏普",
    "Sortino": "索提诺",
    "Portfolio Summary": "组合概览",
    "Portfolio Earnings": "组合资产曲线",
    "Value of": "初始资金",
    "P&L": "盈亏",
    "Performance Metrics": "绩效指标",
    "Key Performance Metrics": "核心绩效指标",
    "Strategy Visualization": "策略图表",
    "Parameters": "参数",
    "Risk-Free Rate": "无风险利率",
    "Periods/Year": "年化周期数",
    "Compounded": "复利计算",
    "Match Dates": "对齐日期",
    "Yes": "是",
    "No": "否",
    "Generated by": "生成工具",
    "Tearsheet": "绩效报告",
    "Strategy Tearsheet": "策略绩效报告",
    "Occurrences": "出现次数",
    "Average": "均值",
    "Backtest": "回测",
    "Log Scaled": "对数坐标",
    "Volatility Matched": "波动率匹配",
    "Cumulative Sum": "累计求和",
    "6-Months": "6个月",
    "12-Months": "12个月",
    "Years": "年份",
    "Daily": "日度",
    "Weekly": "周度",
    "Monthly": "月度",
    "Quarterly": "季度",
    "Yearly": "年度",
    "Annual": "年度",
    "Jan": "1月",
    "Feb": "2月",
    "Mar": "3月",
    "Apr": "4月",
    "May": "5月",
    "Jun": "6月",
    "Jul": "7月",
    "Aug": "8月",
    "Sep": "9月",
    "Oct": "10月",
    "Nov": "11月",
    "Dec": "12月",
    "download report": "下载报告",
    "no drawdowns": "无回撤",
}


METRIC_MAP = {
    "Start Period": "开始日期",
    "End Period": "结束日期",
    "Risk-Free Rate %": "无风险利率 %",
    "Time in Market %": "市场暴露时间 %",
    "Cumulative Return %": "累计收益 %",
    "CAGR﹪%": "年化收益 %",
    "Sharpe": "夏普比率",
    "Prob. Sharpe Ratio %": "夏普显著概率 %",
    "Smart Sharpe": "智能夏普比率",
    "Sortino": "索提诺比率",
    "Smart Sortino": "智能索提诺比率",
    "Sortino/√2": "索提诺/√2",
    "Smart Sortino/√2": "智能索提诺/√2",
    "Omega": "Omega 比率",
    "Max Drawdown %": "最大回撤 %",
    "Longest DD Days": "最长回撤天数",
    "Max DD Date": "最大回撤日期",
    "Max DD Period Start": "最大回撤开始",
    "Max DD Period End": "最大回撤结束",
    "Volatility (ann.) %": "年化波动率 %",
    "Calmar": "Calmar 比率",
    "Skew": "偏度",
    "Kurtosis": "峰度",
    "Expected Daily %%": "期望日收益 %",
    "Expected Monthly %%": "期望月收益 %",
    "Expected Yearly %%": "期望年收益 %",
    "Kelly Criterion %": "Kelly 仓位 %",
    "Risk of Ruin %": "破产风险 %",
    "Ulcer Performance Index": "溃疡绩效指数",
    "Risk-Adjusted Return %": "风险调整收益 %",
    "Risk-Return Ratio": "风险收益比",
    "Daily Value-at-Risk %": "日 VaR %",
    "Expected Shortfall (cVaR) %": "条件 VaR %",
    "Max Consecutive Wins": "最大连续盈利天数",
    "Max Consecutive Losses": "最大连续亏损天数",
    "Gain/Pain Ratio": "收益痛苦比",
    "Gain/Pain (1M)": "月度收益痛苦比",
    "Payoff Ratio": "盈亏赔率",
    "Profit Ratio": "盈利比率",
    "Profit Factor": "盈利因子",
    "Common Sense Ratio": "常识比率",
    "CPC Index": "CPC 指数",
    "Tail Ratio": "尾部比率",
    "Outlier Win Ratio": "异常盈利比率",
    "Outlier Loss Ratio": "异常亏损比率",
    "MTD %": "本月至今 %",
    "3M %": "近 3 月 %",
    "6M %": "近 6 月 %",
    "YTD %": "年初至今 %",
    "1Y %": "近 1 年 %",
    "3Y (ann.) %": "近 3 年年化 %",
    "5Y (ann.) %": "近 5 年年化 %",
    "10Y (ann.) %": "近 10 年年化 %",
    "All-time (ann.) %": "全样本年化 %",
    "Best Day %": "最佳单日 %",
    "Worst Day %": "最差单日 %",
    "Best Month %": "最佳单月 %",
    "Worst Month %": "最差单月 %",
    "Best Year %": "最佳年度 %",
    "Worst Year %": "最差年度 %",
    "Recovery Factor": "恢复因子",
    "Ulcer Index": "溃疡指数",
    "Serenity Index": "平静指数",
    "Avg. Up Month %": "平均上涨月份 %",
    "Avg. Down Month %": "平均下跌月份 %",
    "Win Days %": "日胜率 %",
    "Win Month %": "月胜率 %",
    "Win Quarter %": "季度胜率 %",
    "Win Year %": "年度胜率 %",
    "Beta": "Beta",
    "Alpha": "Alpha",
    "Correlation": "相关系数",
    "Treynor Ratio": "特雷诺比率",
    "Information Ratio": "信息比率",
    "Tracking Error": "跟踪误差",
    "R-Squared": "R 平方",
    "Avg. Drawdown %": "平均回撤 %",
    "Avg. Drawdown Days": "平均回撤天数",
    "Avg. Win %": "平均盈利 %",
    "Avg. Loss %": "平均亏损 %",
    "Win/Loss Ratio": "胜负比",
}


COLUMN_MAP = {
    "Started": "开始",
    "Recovered": "修复",
    "Drawdown": "回撤",
    "Days": "天数",
    "Benchmark": "基准",
    "Strategy": "策略",
    "Returns": "收益率",
    "Multiplier": "倍数",
    "Won": "胜出",
    "Parameter": "参数",
    "Value": "取值",
    "Year": "年份",
    "Month": "月份",
    "Daily": "日度",
    "Weekly": "周度",
    "Monthly": "月度",
    "Quarterly": "季度",
    "Yearly": "年度",
}


def zh_text(value: Any) -> Any:
    """把常见英文展示文本转换为中文；非字符串原样返回。"""
    if not isinstance(value, str):
        return value
    text = TEXT_MAP.get(value, value)
    for eng, cn in sorted(TEXT_MAP.items(), key=lambda item: len(item[0]), reverse=True):
        text = text.replace(eng, cn)
    text = re.sub(r"\bvs\b", "vs", text)
    return text


def zh_metric(value: Any) -> Any:
    """把指标名称转换为中文，找不到精确映射时再做通用文本替换。"""
    if not isinstance(value, str):
        return value
    return METRIC_MAP.get(value, zh_text(value))


def zh_columns(df: pd.DataFrame) -> pd.DataFrame:
    """翻译 DataFrame 的列名，常用于报告表格输出前。"""
    out = df.copy()
    out.columns = [COLUMN_MAP.get(str(col), zh_text(str(col))) for col in out.columns]
    return out


def zh_index(df: pd.DataFrame) -> pd.DataFrame:
    """翻译 DataFrame 的索引名称，常用于指标表输出前。"""
    out = df.copy()
    out.index = [zh_metric(idx) for idx in out.index]
    return out


def zh_html(html: str) -> str:
    """对最终 HTML 做兜底中文替换，覆盖模板和 SVG 中遗留的常见英文标签。"""
    text = html
    combined = {**TEXT_MAP, **METRIC_MAP, **COLUMN_MAP}
    for eng, cn in sorted(combined.items(), key=lambda item: len(item[0]), reverse=True):
        text = text.replace(eng, cn)
    return text
